version: "3.1"

services:
  woocommerce:
    container_name: woocommerce
    build:
      context: docker/ngrok
      dockerfile: Dockerfile
      args:
        WOO_VERSION: 3.7.0 # Woocommerce version to use.
        BILLMATE_VERSION: dev # Tag number or branch name at github to use for the Billmate plugin
    ports:
      - 8282:80
    environment:

      # These values are used for the wp-data base setup and are required.
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: woo_db

      # These values are used in the initial wp setup.
      # Missing values will be filled with dull defaults.
      # Please pay special attention to WP_URL, and make sure that it ends with the same port number that is exposed to the external network.
      WP_URL: localhost:8282 # Default is 'localhost'
      WP_TITLE: MyStore # Default is 'Test-title'
      WP_ADMIN_USER: admin # Default is 'test'
      WP_ADMIN_EMAIL: test@test.se # Default is 'test-admin@test.se'
      WP_ADMIN_PASSWORD: 4dm1n # Default is 'test'
      WPLANG: sv_SE # Swedish as default language
    volumes:
      - ./src:/usr/src/billmate
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: woo_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    ports:
      - 3366:3306
    volumes:
      - ./data/site-dump.sql:/docker-entrypoint-initdb.d/site-dump.sql


  ngrok:
    container_name: ngrok
    ports:
      - "0.0.0.0:4040:4040"
    image: wernight/ngrok
    links:
      - "woocommerce"
    environment:
      - NGROK_AUTH # Set this to your ngrok token, or better yet set this value in a .env file see: https://docs.docker.com/compose/environment-variables/#the-env-file
      - NGROK_REGION=eu
      - NGROK_PORT=woocommerce:80

